---
name: Example
version: 1.0.6
slug: example
description: Example addon - hassos-apps
url: https://github.com/hassos-apps/addon-example
image: ghcr.io/hassos-apps/example-{arch}
init: false
startup: application
arch:
  - aarch64
  - amd64
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
